name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3']
        composer-flags: ['']
        include:
          - php: '8.0'
            composer-flags: '--prefer-stable --prefer-lowest'

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, intl
        coverage: xdebug

    - name: Install dependencies
      run: composer update ${{ matrix.composer-flags }} --prefer-dist --no-interaction

    - name: Run tests
      run: vendor/bin/phpunit --configuration phpunit.xml.ci

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.php }}-${{ matrix.composer-flags }}
        path: build/coverage.xml
